[2024-12-16 03:00:20,751] INFO [GroupCoordinator 1]: Removed 0 offsets associated with deleted partitions: fullfillment.test.customers-0. (kafka.coordinator.group.GroupCoordinator)
[2024-12-16 03:05:20,859] ERROR Error while reading checkpoint file /opt/kafka/logs/kafka-logs/cleaner-offset-checkpoint (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.nio.file.NoSuchFileException: /opt/kafka/logs/kafka-logs/cleaner-offset-checkpoint
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at org.apache.kafka.server.common.CheckpointFile.read(CheckpointFile.java:92)
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.read(CheckpointFileWithFailureHandler.java:75)
	at kafka.server.checkpoints.OffsetCheckpointFile.read(OffsetCheckpointFile.scala:75)
	at kafka.log.LogCleanerManager.$anonfun$allCleanerCheckpoints$2(LogCleanerManager.scala:147)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.flatMap(Iterable.scala:686)
	at scala.collection.IterableOps.flatMap$(Iterable.scala:686)
	at scala.collection.AbstractIterable.flatMap(Iterable.scala:935)
	at kafka.log.LogCleanerManager.$anonfun$allCleanerCheckpoints$1(LogCleanerManager.scala:145)
	at kafka.log.LogCleanerManager.allCleanerCheckpoints(LogCleanerManager.scala:153)
	at kafka.log.LogCleanerManager.$anonfun$grabFilthiestCompactedLog$1(LogCleanerManager.scala:184)
	at kafka.log.LogCleanerManager.grabFilthiestCompactedLog(LogCleanerManager.scala:181)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:412)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:399)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:385)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
[2024-12-16 03:05:20,885] WARN [ReplicaManager broker=1] Stopping serving replicas in dir /opt/kafka/logs/kafka-logs with uuid None because the log directory has failed. (kafka.server.ReplicaManager)
[2024-12-16 03:05:20,914] WARN [ReplicaManager broker=1] Broker 1 stopped fetcher for partitions  and stopped moving logs for partitions  because they are in the failed log directory /opt/kafka/logs/kafka-logs. (kafka.server.ReplicaManager)
[2024-12-16 03:05:20,915] WARN Stopping serving logs in dir /opt/kafka/logs/kafka-logs (kafka.log.LogManager)
[2024-12-16 03:05:20,924] ERROR Shutdown broker because all log dirs in /opt/kafka/logs/kafka-logs have failed (kafka.log.LogManager)
